### ISSUE TITLE
Datapack

### ISSUE THREAD

**Issue by MinecraftPerson** [ExpensiveKoala/Fishing-Real#14]
Hey, I was just wondering if I could get some help making my own data pack for this mod, I've tried to make one, but it never works. I know I'm obviously doing something wrong, but I can't figure out what. It would be nice if I got some step-by-step instructions on how to do it. Thanks!

PS: you should make it so a fish entity has to bite the line for you to reel it in, if that's possible?

**Comment by ExpensiveKoala** [comment]
Reference these articles:
https://minecraft.fandom.com/wiki/Data_pack
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

And create a datapack containing files similarly to https://github.com/ExpensiveKoala/Fishing-Real/tree/master/src/main/resources/data

Some more helpful links:
https://www.curseforge.com/minecraft/mc-mods/fishing-real?page=2#c97
https://github.com/EnigmaticaModpacks/Enigmatica5/tree/master/openloader/data/Enigmatica%205%20Datapack/data/enigmatica

**Comment by ExpensiveKoala** [comment]
> PS: you should make it so a fish entity has to bite the line for you to reel it in, if that's possible?

While possible, this would require a much more significant change to the way fishing is handled and can be prone to breaking other mods. Perhaps this would be better suited as a new/different mod.

**Comment by MinecraftPerson** [comment]
Is it possible you know a mod that adds this feature?

**Comment by ExpensiveKoala** [comment]
Not in any recent versions of minecraft.
There was a mod that added fish and had this type of fishing mechanic in 1.6.2
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1277176-1-6-2-1-5-2-forge-smp-comicretrolutions-craftory
