### ISSUE TITLE
Datapack works selectively with one modded entity

### ISSUE THREAD

**Issue by Kelpiesaurus** [ExpensiveKoala/Fishing-Real#17]
I created a datapack to convert items to entities as suggested on the mod's Curseforge page, and it fails to convert the koi fish from Critters and Companions version 1.18.2-1.0.2. It successfully converts the koi in versions 1.19.2-1.1.2 and 1.19.2-1.0.2. 

My 1.18.2 datapack has the proper pack format and successfully converts other modded fish (e.g. upgrade_aquatic:nautilus). 

I asked the author of the Critters and Companions mod about it, and they responded: "Koi fish is exactly the same entity in 1.0.2 and 1.1.2."

This is what I have in the json:

{
  "input": {
    "item": "crittersandcompanions:koi_fish"
  },
  "result": {
    "id": "crittersandcompanions:koi_fish"
  }
}

**Comment by ExpensiveKoala** [comment]
I'd have to look at the code for Critters and Companions to confirm, but I believe this is caused by either the item, or the entity's registration being different. Check the item's registry name with f3+h in game. For entity, it's going to be the same as the /summon <entity_id>.

**Comment by ndcregut** [comment]
I'm having the same issues with Aquaculture 2 fish

**Comment by ExpensiveKoala** [comment]
Can you post your datapack folder structure and some of the jsons that are failing?

**Comment by ndcregut** [comment]
issue resolved, i didn't name the folder properly
