### ISSUE TITLE
Compat: Aquaculture bait consumption and double fish chance

### ISSUE THREAD

**Issue by ExpensiveKoala** [ExpensiveKoala/Fishing-Real#19]
https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/entity/AquaFishingBobberEntity.java#L170-L192

As was brought up in #18, the current support for Aquaculture is very limited.
Bait consumption and Double fish chance happen after the first ItemFishedEvent fires (and gets cancelled) so they never happen.

**Comment by sisby-folk** [comment]
Noting down on this one - this *can* be resolved using explicit an explicit compatibility patch if that's desired - not sure how else you'd do it without a fancy mixin extension I don't know about.

Basically you'd make an identical mixin to the new retrieve mixin that instead targets the custom aquaculture bobber explicitly - then turn off the forge method for those bobbers.
