### ISSUE TITLE
Crashing after updating to 1.6

### ISSUE THREAD

**Issue by peppe0888** [ExpensiveKoala/Fishing-Real#21]
Hi, for some context, i have a small server where i play with my friends, used the mod and worked flawlessly, but since i updated to 1.6 both the server and client continue crashing. I verified by downgrading the mod that it only happens with the 1.6 version
Here is the log, i suck at reading logs so i can't really understand the issue
https://mclo.gs/NyDFLpp

**Comment by ExpensiveKoala** [comment]
Thanks! I didn't catch this. Uploading hotfix now.
