### ISSUE TITLE
[1.20.1] Crash when launchig with Aquaculture

### ISSUE THREAD

**Issue by MrKashew** [ExpensiveKoala/Fishing-Real#22]
[crash-2023-07-11_12.24.10-client.txt](https://github.com/ExpensiveKoala/Fishing-Real/files/12018378/crash-2023-07-11_12.24.10-client.txt)
Haven't tried using the 1.19.4 datapack for aquaculture yet however

**Comment by ExpensiveKoala** [comment]
Thanks! I didn't catch this. Uploading hotfix now.
