### ISSUE TITLE
Can You Be Completely Authentic?

### ISSUE THREAD

**Issue by likknnjhoson** [ExpensiveKoala/Fishing-Real#24]
I Want To Fish When It Comes To Real Fishing Because Many Mods Can't Do That.
![Không Có Tiêu Đề111_20230713180129](https://github.com/ExpensiveKoala/Fishing-Real/assets/111974986/8bf6ef92-9070-4ee6-857a-436eca6d294b)

**Comment by ExpensiveKoala** [comment]
I'm assuming you mean to have actual fish mobs go towards the bobber.

Unfortunately, this would fall outside the scope of this mod.
Achieving this would require two things:
1. Adding custom AI to all "fishable" entities.
2. Changing the behavior of the fishing hook entity.

Fishing Real is made to be compatible with other mods, so the fishing hook behavior change would be very breaking. Also, it is unclear if the custom AI would break other mods' entities.

**Comment by likknnjhoson** [comment]
Cách Làm Một Ai Như Thế Là Như Thế Nào?
