### ISSUE TITLE
Aquaculture 2 only fish entities

### ISSUE THREAD

**Issue by ClockworkzAI** [ExpensiveKoala/Fishing-Real#25]
1.19.2 Forge 
version Fishingreal-1.19.2-1.6.1.jar

Aquaculture-1.19.2-2.4.8.jar

Fish pulls from rod only spawn item and not the mob
Have tried with data pack and without data pack
How do you fix this?

the mob fish seemed to have the same name as the item and not the spawn egg.
![image](https://github.com/ExpensiveKoala/Fishing-Real/assets/87075658/c40d6055-c5d4-4ca2-bd42-b4f1747b5370)
![image](https://github.com/ExpensiveKoala/Fishing-Real/assets/87075658/357270b2-ed51-493f-a165-6d992605a5ee)

**Comment by ExpensiveKoala** [comment]
Can you share more info on your datapack? How you installed it, where&what files you included, etc..

**Comment by ClockworkzAI** [comment]
i installed it using curse forge https://www.curseforge.com/minecraft/customization/fishing-real-aquaculture-datapack im using this datapack with open with Global Packs mod to load the datapack

**Comment by ExpensiveKoala** [comment]
I am not familiar with how Global Packs works, but the datapack works with manual installation into the datapacks folder of the world. This seems to be more of an issue for Global Packs than Fishing Reel.
