### ISSUE TITLE
[Feature Request] Fished fish should be spawned in the location where it was fished up, instead of being spawned elsewhere and moved there

### ISSUE THREAD

**Issue by thelegitdolt** [ExpensiveKoala/Fishing-Real#26]
This does not matter with vanilla fishes, but I am currently playing a mod called Environmental which adds a fish which use a noise-based system to determine what variant should be spawned based on the world coordinate. However, since fishing real always spawns the fish at some set location and, all fished koi will only be 1 set variant that will rarely be the same variant as the koi that would naturally spawn there. 

This feature wouldn't really affect fishes in vanilla, but should patch up other edge cases where some fish mobs have variants depending on the coordinate/biome spawned. I would really appreciate, thank you

**Comment by ExpensiveKoala** [comment]
This issue comes from the entity position being set after the finalize spawn which is where variant selection occurs instead of before.
