### ISSUE TITLE
Optional Result per Input in Datapack

### ISSUE THREAD

**Issue by Dark-Arcana** [ExpensiveKoala/Fishing-Real#6]
Hello! I'm using this mod in an upcoming modpack, soon to be released. I really love the concept of fishing up random fish that are alive. But it would be nice if we could have optional results. For example, it could have a weight to gather an item or the living mob entity, or even some other loot table entry.

```
{
  "input": {
    "name": "minecraft:salmon"
  },
  "result": [
    {
      "type": "item",
      "name": "minecraft:salmon",
      "weight": 10
    },
    {
      "type": "entity",
      "name": "minecraft:salmon",
      "weight": 5
    },
    {
      "type": "loot_table",
      "name": "namespace:chests/fishing_treasure",
      "weight": 1
    }
  ]
}
```

These changes could make the mod Fishing Real very versatile allowing modpacks/datapack creators to provide new play experiences. Please let me know if you'd be interested in adding these features.

**Comment by ExpensiveKoala** [comment]
You can actually already achieve this. (kinda)
The mod only does a item->entity replacement and doesn't really care what the original item or the resulting entity is.

Meaning you can actually just add a datapack to change the fishing loottable to include random placeholder items and have this mod replace that placeholder item with the entity/item you are wanting at the rarity you want.

So to achieve your example:
Fishing Loot Table:
```json
{
  "type": "minecraft:fishing",
  "pools": [
    {
      "rolls": 1,
      "bonus_rolls": 0,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:salmon",
          "weight": 10,
          "functions": [
            {
              "function": "set_count",
              "count": {
                "min": 0,
                "max": 1
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:anvil",
          "weight": 5,
          "functions": [
            {
              "function": "set_count",
              "count": {
                "min": 0,
                "max": 1
              }
            }
          ]
        },
        {
          "type": "minecraft:loot_table",
          "name": "namespace:chests/fishing_treasure",
          "weight": 1,
          "functions": [
            {
              "function": "set_count",
              "count": {
                "min": 0,
                "max": 1
              }
            }
          ]
        }
      ]
    }
  ]
}
```

and you might have just a simple Fishing Real datapack entry like so:

```json
{
    "input": {
        "item": "minecraft:anvil"
    },
    "result": {
        "id": "minecraft:salmon"
    }
}
```


I feel this is better as it doesn't try to turn the datapack of this mod into another loot table.

**Comment by Dark-Arcana** [comment]
Thanks for the response!
