### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by migueldns** [ExpensiveKoala/Fishing-Real#7]
Hey.. I'm not sure if this is the correct section to make suggestions; so sorry if its not but I have a request. I really want to add fish from Aquaculture 2 to Fishing Real and I have looked absolutely everywhere for a tutorial how but have had no hope. I created a folder named fishing inside my servers datapacks like the instructions insisted and placed all the fishes jsons or something. Sadly that did nothing.

**Comment by ExpensiveKoala** [comment]
Please ensure that you are following the proper format for [datapacks](https://minecraft.fandom.com/wiki/Data_pack#Folder_structure).

So it should look like:
[Your world folder] -> datapacks -> [Datapack folder] -> data -> [A Namespace (could be anything)] -> fishing
