### ISSUE TITLE
Failed to load correctly in latest forge versions

### ISSUE THREAD

**Issue by Nalwyn603** [ExpensiveKoala/Fishing-Real#8]
In the latest forge versions the 1.18.x version of the mod gets the "failed to load correctly" error, specifying "java.lang.NoClassDefFoundError: net/minecraft/tags/Tag$Named

**Comment by wendall911** [comment]
This isn't yet released for 1.18.2. I provided a PR for this. Hopefully the author publishes this soon.

**Comment by ExpensiveKoala** [comment]
Just released the update. Thanks!
Also did the 1.19 update as well.
